# Generated by Django 3.0.6 on 2020-08-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200721_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
